# Generated by Django 4.2 on 2023-05-02 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="predictionModel1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thumb", models.ImageField(upload_to="prediction_model1")),
                (
                    "category",
                    models.IntegerField(
                        choices=[(1, "Gaming"), (2, "Development"), (3, "Cars")]
                    ),
                ),
                ("subscribers", models.IntegerField(default=0)),
                (
                    "channel_pub_time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "video_pub_time",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("videos", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
