# Generated by Django 4.0.7 on 2023-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_tokenbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPromotable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
